apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc-data
  namespace: monitoring
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      usage: grafana-pv-data
