apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: mr-do-observer
spec:
  selector:
    app: grafana
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000