### Create a ServiceMonitor for the pod’s namespace
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: mr-do-observer # Prometheus namespace
  labels:
    name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'kubernetes-nodes'
        static_configs:
          - targets: ['localhost:9100']
      - job_name: 'metallb'
        metrics_path: /metrics
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace]
            action: keep
            regex: metallb-system
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: metallb

