apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: mr-do-observer
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090