### Create a ServiceMonitor for the pod’s namespace
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: mr-do-observer # Prometheus namespace
  labels:
    name: prometheus-config
#data:
#  prometheus.yml: |
#    global:
#      scrape_interval: 15s
#    scrape_configs:
#      - job_name: 'kubernetes-nodes'
#        static_configs:
#          - targets: ['localhost:9100']
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - source_labels: [__address__]
            action: replace
            target_label: instance
