apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-kubelet-scraper
  namespace: monitoring
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/metrics
      - nodes/proxy
      - pods
      - services
      - endpoints
    verbs: ["get", "list", "watch"]
#  - apiGroups: ["metrics.k8s.io"]
#    resources:
#      - nodes
#      - pods
#    verbs: ["get", "list"]
