apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
spec:
  selector:
    app: prometheus
  type: LoadBalancer
  loadBalancerIP: 192.168.0.12
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: http
