apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-service-monitor
  namespace: mr-do-observer
spec:
  selector:
    matchLabels:
      app: prometheus
  endpoints:
    - port: 9090
      interval: 15s