apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: traffic-monitoring
  namespace: mr-do-observer
spec:
  selector:
    matchLabels:
      app: mr-do-player
  endpoints:
    - port: 9100
      interval: 15s
