apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv-data
  labels:
    usage: prometheus-pv-data
spec:
  capacity:
    storage: 10Gi
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: mr0.local
    path: "/srv/nfs4/homes/mr/observer/prometheus/"
    readOnly: false
